# Use official MySQL 8.0.33 as base image, some changes to trigger pipeline.
FROM mysql:8.0.33

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=mydb
#ENV MYSQL_USER=root


