# Use OpenJDK 17 Alpine base image.
FROM openjdk:17-jdk-alpine

# Expose port 8080
EXPOSE 8090

COPY ./target/demo-1.0.0.jar ./

# Just a placeholder command to keep the container running
CMD ["java", "-jar", "demo-1.0.0.jar"]

